export const TOKENS = {
    colors: {
        yolk: "#F8E71C",
        ultraviolet: "#4C00FF",
        white: "#FFFFFF",
        lightgray: "#C0C0C0",
        gray: "#666666",
        darkgray: "#232323",
        black: "#000000",
    },
    typography: {
        title: {
            fontFamily: "Roundabout-Regular, Urbanist, sans-serif",
            fontSize: 16,
        },
        body: {
            fontFamily: "Roundabout-Regular, Sulphur Point, sans-serif",
            fontSize: 16,
        },
        digitBig: {
            fontFamily: "4pixel, monospace",
            fontSize: 10,
        },
        digitSmall: {
            fontFamily: "4pixel, monospace",
            fontSize: 5,
        },
        code: {
            fontFamily: "'Courier New', monospace",
            fontSize: 12,
        },
    },
    sizes: {
        DOT_1: 1, // 1px
        CIRCLE_4: 4,
        CIRCLE_6: 6,
        CIRCLE_61: 61,
        MINI_CARD: 31,
        MINI_PAGINATOR: 4,
        MINI_PAGINATOR_GAP: 2,
        BIG_PAGINATOR_W: 17,
        BIG_PAGINATOR_H: 4,
        BIG_PAGINATOR_GAP: 0,
        RECTANGLE_SMALL_W: 4,
        RECTANGLE_SMALL_H: 17,
        MID_CARD_W: 83,
        MID_CARD_H: 109,
        TAB_W: 109,
        TAB_H: 23,
        BLUR_PLAYGROUND: 16,
        STROKE: 1,
        HUD_PADDING: 2, // New token
    },
    zIndexes: {
        HUD_Z_Index: 10,
    },
    gameConstants: {
        energyGenerationRate: 0.1,
        particleRadius: 3,
        quantaUnit: 1.602176634e-19,
        playgroundDebugArtMode: false,
    },
} as const;

// CSS Variables for global use
export const CSS_VARS = {
    '--color-yolk': TOKENS.colors.yolk,
    '--color-ulatraviolet': TOKENS.colors.ultraviolet,
    '--color-white': TOKENS.colors.white,
    '--color-light-gray': TOKENS.colors.lightgray,
    '--color-gray': TOKENS.colors.gray,
    '--color-dark-gray': TOKENS.colors.darkgray,
    '--color-black': TOKENS.colors.black,

    '--font-title': TOKENS.typography.title.fontFamily,
    '--font-title-size': `${TOKENS.typography.title.fontSize}px`,
    '--font-body': TOKENS.typography.body.fontFamily,
    '--font-body-size': `${TOKENS.typography.body.fontSize}px`,
    '--font-digit-big': TOKENS.typography.digitBig.fontFamily,
    '--font-digit-big-size': `${TOKENS.typography.digitBig.fontSize}px`,
    '--font-digit-small': TOKENS.typography.digitSmall.fontFamily,
    '--font-digit-small-size': `${TOKENS.typography.digitSmall.fontSize}px`,
    '--font-digit-size': `${TOKENS.typography.digitBig.fontSize}px`,
    '--font-code': TOKENS.typography.code.fontFamily,
    '--font-code-size': `${TOKENS.typography.code.fontSize}px`,

    '--size-hud-padding': `${TOKENS.sizes.HUD_PADDING}px`,
    '--z-index-hud': TOKENS.zIndexes.HUD_Z_Index,
    '--size-dot-1': `${TOKENS.sizes.DOT_1}px`,
    '--size-circle-4': `${TOKENS.sizes.CIRCLE_4}px`,
    '--size-circle-6': `${TOKENS.sizes.CIRCLE_6}px`,
    '--size-circle-61': `${TOKENS.sizes.CIRCLE_61}px`,
    '--size-mini-card': `${TOKENS.sizes.MINI_CARD}px`,
    '--size-mini-paginator': `${TOKENS.sizes.MINI_PAGINATOR}px`,
    '--size-mini-paginator-gap': `${TOKENS.sizes.MINI_PAGINATOR_GAP}px`,
    '--size-big-paginator-w': `${TOKENS.sizes.BIG_PAGINATOR_W}px`,
    '--size-big-paginator-h': `${TOKENS.sizes.BIG_PAGINATOR_H}px`,
    '--size-big-paginator-gap': `${TOKENS.sizes.BIG_PAGINATOR_GAP}px`,
    '--size-rectangle-small-w': `${TOKENS.sizes.RECTANGLE_SMALL_W}px`,
    '--size-rectangle-small-h': `${TOKENS.sizes.RECTANGLE_SMALL_H}px`,
    '--size-mid-card-w': `${TOKENS.sizes.MID_CARD_W}px`,
    '--size-mid-card-h': `${TOKENS.sizes.MID_CARD_H}px`,
    '--size-tab-w': `${TOKENS.sizes.TAB_W}px`,
    '--size-tab-h': `${TOKENS.sizes.TAB_H}px`,
    '--size-blur-playground': `${TOKENS.sizes.BLUR_PLAYGROUND}px`,
    '--size-stroke': `${TOKENS.sizes.STROKE}px`,
} as const;