/**
 * Visual Design Tokens
 * 
 * This file contains visual design parameters for the UI system including:
 * - Colors, typography, sizes, spacing, and z-index values
 * - CSS variables for consistent styling across components
 * 
 * For game logic constants, see: src/lib/constants/game-constants.ts
 */
export const TOKENS = {
    // Colors
    colors: {
        yolk: "#F8E71C",
        ultraviolet: "#4C00FF",
        white: "#FFFFF5",
        lightgray: "#C0C0C0",
        gray: "#666666",
        darkgray: "#232323",
        black: "#000000",

        // QCD Color Charge - Matter Quarks
        qcdRedStart: "#FC9938", qcdRedEnd: "#F83284",
        qcdGreenStart: "#F0F340", qcdGreenEnd: "#3EA968",
        qcdBlueStart: "#4EDFF8", qcdBlueEnd: "#5554F5",

        // QCD Color Charge - Antimatter Quarks (Anticolors)
        qcdCyanStart: "#95F2F4", qcdCyanEnd: "#59C4F6",
        qcdMagentaStart: "#C86DD7", qcdMagentaEnd: "#782AF7",
        qcdYellowStart: "#F8E71C", qcdYellowEnd: "#FD9A3E",
    },
    // Typography
    typography: {
        title: {
            fontFamily: "Roundabout-Regular, Urbanist, sans-serif",
            fontSize: 16,
        },
        body: {
            fontFamily: "Roundabout-Regular, Sulphur Point, sans-serif",
            fontSize: 16,
        },
        digitBig: {
            fontFamily: "'4pixel', monospace",
            fontSize: 10,
        },
        digitSmall: {
            fontFamily: "'4pixel', monospace",
            fontSize: 5,
        },
        code: {
            fontFamily: "'Courier New', monospace",
            fontSize: 12,
        },
    },
    // Sizes
    sizes: {
        // Circle sizes
        CIRCLE_DOT_1: 1, // 1px
        CIRCLE_MICRO_4: 4,
        CIRCLE_MINI_6: 6,
        CIRCLE_MIDDLE_61: 61,
        CIRCLE_MEGA_109: 109,

        // Card sizes
        CARD_SMALL: 31,
        CARD_MID_W: 83,
        CARD_MID_H: 109,
        CARD_BIG: 175,
        CARD_BIG_W: 311,
        CARD_BIG_H: 503,

        // Component sizes
        SQUARE_SMALL: 4,
        RECTANGLE_SMALL: 17,
        TAB_MIN_W: 109,
        TAB_H: 23,
        BUTTON_MIN_WIDTH: 175,
        BUTTON_HEIGHT: 31,
        BLUR_PLAYGROUND: 16,
        BLUR_SMALL: 4,
        LINE: 1,

        // Gap sizes
        GAP_SMALL: 2,
        GAP_LARGE: 16,

        // Padding sizes
        PADDING_SMALL: 4,
        PADDING_MEDIUM: 8,

        // Margin sizes
        MARGIN_SMALL: 8,

        // Border radius
        BORDER_RADIUS_SMALL: 4,

        // Other sizes
        OUTLINE_OFFSET: 2,
        ANIMATION_TRANSLATE_UP: 1,

        // Playground specific sizes
        PLAYGROUND_MARGIN: 2, // Margin around playground circle
        PLAYGROUND_SHADOW_OPACITY: 0.1, // Shadow opacity for bottom blur
        PLAYGROUND_SHADOW_OFFSET: 0.5, // Shadow offset ratio (0.5 = half radius)

    },
    // Shadows
    // TODO: check this are we using this list of shadows, looks autogenerated, keep here only that is used.
    shadows: {
        textSubtle: "0 1px 2px rgba(0, 0, 0, 0.5)",
        boxSubtle: "0 2px 8px rgba(0, 0, 0, 0.1)",
        boxMedium: "0 4px 16px rgba(0, 0, 0, 0.15)",
        boxStrong: "0 8px 32px rgba(0, 0, 0, 0.2)",
    },

    // Shadow sizes (electrons)
    shadowSizes: {
        SMALL: 17,
        MID: 40,
        BIG: 109,
    },

    // Shadow gradients
    shadowGradients: {
        particleMatter: 'radial-gradient(circle, rgba(248, 231, 28, 0.3) 0%, rgba(248, 231, 28, 0.1) 50%, transparent 100%)',
        particleAntimatter: 'radial-gradient(circle, rgba(76, 0, 255, 0.3) 0%, rgba(76, 0, 255, 0.1) 50%, transparent 100%)',
        quarkDepth: 'radial-gradient(circle, rgba(0, 0, 0, 1) 0%, rgba(0, 0, 0, 0.5) 50%, rgba(0, 0, 0, 0) 100%)',
    },

    // QCD Color Charge Gradients for Quarks
    qcdGradients: {
        // Matter Quarks - 3D sphere gradients (light center to dark edge)
        red: 'radial-gradient(circle at 30% 30%, #FC9938 0%, #F83284 100%)',
        green: 'radial-gradient(circle at 30% 30%, #F0F340 0%, #3EA968 100%)',
        blue: 'radial-gradient(circle at 30% 30%, #4EDFF8 0%, #5554F5 100%)',

        // Antimatter Quarks (Anticolors) - 3D sphere gradients (light center to dark edge)
        cyan: 'radial-gradient(circle at 30% 30%, #95F2F4 0%, #59C4F6 100%)',
        magenta: 'radial-gradient(circle at 30% 30%, #C86DD7 0%, #782AF7 100%)',
        yellow: 'radial-gradient(circle at 30% 30%, #F8E71C 0%, #FD9A3E 100%)',
    },

    // Quark shadow configuration
    quarkShadow: {
        extension: 2, // Shadow extends 2px beyond particle diameter on each side
    },
    // Z-indexes
    zIndexes: {
        HUD_Z_Index: 10,
    },
} as const;

// CSS Variables for global use
export const CSS_VARS = {
    '--color-yolk': TOKENS.colors.yolk,
    '--color-ultraviolet': TOKENS.colors.ultraviolet,
    '--color-white': TOKENS.colors.white,
    '--color-light-gray': TOKENS.colors.lightgray,
    '--color-gray': TOKENS.colors.gray,
    '--color-dark-gray': TOKENS.colors.darkgray,
    '--color-black': TOKENS.colors.black,
    '--color-transparent': 'transparent',

    // QCD Color Charge Colors
    '--qcd-red-start': TOKENS.colors.qcdRedStart,
    '--qcd-red-end': TOKENS.colors.qcdRedEnd,
    '--qcd-green-start': TOKENS.colors.qcdGreenStart,
    '--qcd-green-end': TOKENS.colors.qcdGreenEnd,
    '--qcd-blue-start': TOKENS.colors.qcdBlueStart,
    '--qcd-blue-end': TOKENS.colors.qcdBlueEnd,
    '--qcd-cyan-start': TOKENS.colors.qcdCyanStart,
    '--qcd-cyan-end': TOKENS.colors.qcdCyanEnd,
    '--qcd-magenta-start': TOKENS.colors.qcdMagentaStart,
    '--qcd-magenta-end': TOKENS.colors.qcdMagentaEnd,
    '--qcd-yellow-start': TOKENS.colors.qcdYellowStart,
    '--qcd-yellow-end': TOKENS.colors.qcdYellowEnd,

    // Particle Colors
    '--particle-lepton-matter': TOKENS.colors.yolk,
    '--particle-lepton-antimatter': TOKENS.colors.ultraviolet,
    '--particle-neutrino-matter': TOKENS.colors.white,
    '--particle-neutrino-antimatter': TOKENS.colors.white,
    '--particle-quark-matter': TOKENS.colors.gray,
    '--particle-quark-antimatter': TOKENS.colors.gray,

    /* Particle Gradients */
    '--gradient-particle-quark-up': '',

    /* Shadows */
    '--shadow-text-subtle': TOKENS.shadows.textSubtle,
    '--shadow-box-subtle': TOKENS.shadows.boxSubtle,
    '--shadow-box-medium': TOKENS.shadows.boxMedium,
    '--shadow-box-strong': TOKENS.shadows.boxStrong,

    // Shadow sizes
    '--shadow-size-small': `${TOKENS.shadowSizes.SMALL}px`,
    '--shadow-size-mid': `${TOKENS.shadowSizes.MID}px`,
    '--shadow-size-big': `${TOKENS.shadowSizes.BIG}px`,

    // Shadow gradients
    '--particle-matter-shadow': TOKENS.shadowGradients.particleMatter,
    '--particle-antimatter-shadow': TOKENS.shadowGradients.particleAntimatter,
    '--quark-depth-shadow': TOKENS.shadowGradients.quarkDepth,

    // QCD Color Charge Gradients
    '--qcd-gradient-red': TOKENS.qcdGradients.red,
    '--qcd-gradient-green': TOKENS.qcdGradients.green,
    '--qcd-gradient-blue': TOKENS.qcdGradients.blue,
    '--qcd-gradient-cyan': TOKENS.qcdGradients.cyan,
    '--qcd-gradient-magenta': TOKENS.qcdGradients.magenta,
    '--qcd-gradient-yellow': TOKENS.qcdGradients.yellow,

    // Quark shadow
    '--quark-shadow-extension': `${TOKENS.quarkShadow.extension}px`,

    // Blurs sizes 
    '--size-blur-playground': `${TOKENS.sizes.BLUR_PLAYGROUND}px`,
    '--size-blur-small': `${TOKENS.sizes.BLUR_SMALL}px`,

    // Fonts
    '--font-title': TOKENS.typography.title.fontFamily,
    '--font-title-size': `${TOKENS.typography.title.fontSize}px`,
    '--font-body': TOKENS.typography.body.fontFamily,
    '--font-body-size': `${TOKENS.typography.body.fontSize}px`,
    '--font-digit-big': TOKENS.typography.digitBig.fontFamily,
    '--font-digit-big-size': `${TOKENS.typography.digitBig.fontSize}px`,
    '--font-digit-small': TOKENS.typography.digitSmall.fontFamily,
    '--font-digit-small-size': `${TOKENS.typography.digitSmall.fontSize}px`,
    '--font-code': TOKENS.typography.code.fontFamily,
    '--font-code-size': `${TOKENS.typography.code.fontSize}px`,

    // Sizes
    '--z-index-hud': TOKENS.zIndexes.HUD_Z_Index,
    '--size-dot-1': `${TOKENS.sizes.CIRCLE_DOT_1}px`,
    '--size-circle-4': `${TOKENS.sizes.CIRCLE_MICRO_4}px`,
    '--size-circle-6': `${TOKENS.sizes.CIRCLE_MINI_6}px`,
    '--size-circle-61': `${TOKENS.sizes.CIRCLE_MIDDLE_61}px`,
    '--size-circle-109': `${TOKENS.sizes.CIRCLE_MEGA_109}px`,

    '--size-square-small': `${TOKENS.sizes.SQUARE_SMALL}px`,
    '--size-rectangle-small': `${TOKENS.sizes.RECTANGLE_SMALL}px`,
    '--size-card-small': `${TOKENS.sizes.CARD_SMALL}px`,
    '--size-card-mid-w': `${TOKENS.sizes.CARD_MID_W}px`,
    '--size-card-mid-h': `${TOKENS.sizes.CARD_MID_H}px`,

    '--size-tab-min-w': `${TOKENS.sizes.TAB_MIN_W}px`,
    '--size-tab-h': `${TOKENS.sizes.TAB_H}px`,

    '--size-button-width': `${TOKENS.sizes.BUTTON_MIN_WIDTH}px`,
    '--size-button-height': `${TOKENS.sizes.BUTTON_HEIGHT}px`,

    '--size-card-big': `${TOKENS.sizes.CARD_BIG}px`,
    '--size-card-big-w': `${TOKENS.sizes.CARD_BIG_W}px`,
    '--size-card-big-h': `${TOKENS.sizes.CARD_BIG_H}px`,

    // lines sizes
    '--size-line': `${TOKENS.sizes.LINE}px`,

    // Gap sizes
    '--size-gap-small': `${TOKENS.sizes.GAP_SMALL}px`,
    '--size-gap-large': `${TOKENS.sizes.GAP_LARGE}px`,

    // Padding sizes
    '--size-padding-small': `${TOKENS.sizes.PADDING_SMALL}px`,
    '--size-padding-medium': `${TOKENS.sizes.PADDING_MEDIUM}px`,

    // Margin sizes
    '--size-margin-small': `${TOKENS.sizes.MARGIN_SMALL}px`,

    // Other sizes
    '--size-outline-offset': `${TOKENS.sizes.OUTLINE_OFFSET}px`,

    // Animation transition
    '--animation-translate-up': `${TOKENS.sizes.ANIMATION_TRANSLATE_UP}px`,

    // Playground specific
    '--playground-margin': `${TOKENS.sizes.PLAYGROUND_MARGIN}px`,
    '--playground-shadow-opacity': TOKENS.sizes.PLAYGROUND_SHADOW_OPACITY,
    '--playground-shadow-offset': TOKENS.sizes.PLAYGROUND_SHADOW_OFFSET,

} as const;